-- create tables

create table d06_prodotto (
    id            number generated by default on null as identity
                  constraint d06_prodotto_id_pk primary key,
    prodotto      varchar2(50 char) not null,
    created       date not null,
    created_by    varchar2(255 char) not null,
    updated       date not null,
    updated_by    varchar2(255 char) not null
);



create table d06_cliente (
    id              number generated by default on null as identity
                    constraint d06_cliente_id_pk primary key,
    cliente         varchar2(50 char) not null,
    zona_cliente    varchar2(10 char) not null,
    created         date not null,
    created_by      varchar2(255 char) not null,
    updated         date not null,
    updated_by      varchar2(255 char) not null
);



create table d06_vendita (
    id             number generated by default on null as identity
                   constraint d06_vendita_id_pk primary key,
    prodotto_id    number                   constraint d06_vendita_prodotto_id_fk
                   references d06_prodotto not null,
    cliente_id     number                   constraint d06_vendita_cliente_id_fk
                   references d06_cliente not null,
    data           date not null,
    quantita       number not null,
    importo        number not null,
    created        date not null,
    created_by     varchar2(255 char) not null,
    updated        date not null,
    updated_by     varchar2(255 char) not null
);

-- table index
create index d06_vendita_i1 on d06_vendita (prodotto_id);

create index d06_vendita_i2 on d06_vendita (cliente_id);



-- triggers
create or replace trigger d06_prodotto_biu
    before insert or update
    on d06_prodotto
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d06_prodotto_biu;
/


create or replace trigger d06_cliente_biu
    before insert or update
    on d06_cliente
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d06_cliente_biu;
/


create or replace trigger d06_vendita_biu
    before insert or update
    on d06_vendita
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d06_vendita_biu;
/


-- Generated by Quick SQL 1.2.9 08/07/2025, 11:41:06

/*
prodotto
  prodotto vc50 /nn

cliente
  cliente vc50 /nn
  zona_cliente vc10 /nn

vendita
  data d /nn
  prodotto_id num /nn /fk prodotto
  cliente_id num /nn /fk cliente
  quantita num /nn
  importo num /nn





 Non-default options:
# settings = {"apex":"Y","auditcols":true,"db":"19c","prefix":"d06","pk":"identity"}

*/
