alter table d09_tipo_prodotto modify id generated by default on null  as identity restart start with 1000;
alter table d09_prodotto      modify id generated by default on null  as identity restart start with 1000;
alter table d09_cliente       modify id generated by default on null  as identity restart start with 1000;
alter table d09_fornitore     modify id generated by default on null  as identity restart start with 1000;
alter table d09_acquisto      modify id generated by default on null  as identity restart start with 1000;
alter table d09_vendita       modify id generated by default on null  as identity restart start with 1000;