-- create tables

create table d09_tipo_prodotto (
    id               number generated by default on null as identity
                     constraint d09_tipo_prodotto_id_pk primary key,
    tipo_prodotto    varchar2(50 char) not null,
    gruppo           varchar2(50 char) not null
);

alter table d09_tipo_prodotto add constraint d09_tipo_prodotto_uk unique (tipo_prodotto);



create table d09_prodotto (
    id                  number generated by default on null as identity
                        constraint d09_prodotto_id_pk primary key,
    prodotto            varchar2(50 char) not null,
    prezzo_acquisto     number not null,
    prezzo_vendita      number not null,
    tipo_prodotto_id    number not null
);

alter table d09_prodotto add constraint d09_prodotto_uk unique (prodotto);



create table d09_cliente (
    id         number generated by default on null as identity
               constraint d09_cliente_id_pk primary key,
    cliente    varchar2(50 char) not null,
    zona       varchar2(10 char) not null
);

alter table d09_cliente add constraint d09_cliente_uk unique ();



create table d09_fornitore (
    id           number generated by default on null as identity
                 constraint d09_fornitore_id_pk primary key,
    fornitore    varchar2(50 char) not null,
    zona         varchar2(50 char) not null
);

alter table d09_fornitore add constraint d09_fornitore_uk unique (fornitore);



create table d09_acquisto (
    id              number generated by default on null as identity
                    constraint d09_acquisto_id_pk primary key,
    data            date not null,
    fornitore_id    number not null,
    prodotto_id     number not null,
    quantita        number not null
);



create table d09_vendita (
    id             number generated by default on null as identity
                   constraint d09_vendita_id_pk primary key,
    data           date not null,
    cliente_id     number not null,
    prodotto_id    number not null,
    quantita       number not null
);



-- Generated by Quick SQL 1.2.9 22/07/2025, 09:39:34

/*
tipo prodotto /unique tipo_prodotto
  tipo_prodotto vc50 /nn 
  gruppo vc50 /nn

prodotto /unique prodotto
  prodotto vc50 /nn 
  prezzo acquisto num /nn
  prezzo vendita num /nn
  tipo_prodotto_id /nn

cliente /unique
  cliente vc50 /nn 
  zona vc10 /nn

fornitore /unique fornitore
  fornitore vc50 /nn 
  zona vc50 /nn

acquisto
  data date /nn
  fornitore_id /nn
  prodotto_id /nn
  quantita num /nn

vendita
  data date /nn
  cliente_id  /nn
  prodotto_id /nn
  quantita num /nn




 Non-default options:
# settings = {"apex":"Y","db":"19c","prefix":"D09","pk":"IDENTITY"}

*/